# Generated by Django 2.2.4 on 2020-06-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('BLACK', 'Черный'), ('WHITE', 'Белый')], default='BLACK', max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомашины',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserTest')),
            ],
        ),
    ]
