# Generated by Django 2.2.4 on 2020-06-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(choices=[('RED', 'Красный'), ('BLACK', 'Черный'), ('WHITE', 'Белый')], default='BLACK', max_length=100)),
                ('type', models.CharField(choices=[('TYPE1', 'TYPE1'), ('TYPE2', 'TYPE2')], default='TYPE1', max_length=100)),
                ('amount_passengers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
