# Generated by Django 2.2.4 on 2020-06-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200615_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_users', to='core.Car'),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_users', to='core.UserTest'),
        ),
    ]
